version: '2.0'
services:
  chatgpt-on-wechat:
    build:
      context: ./
      dockerfile: Dockerfile.alpine
    image: zhayujie/chatgpt-on-wechat
    container_name: sample-chatgpt-on-wechat
    environment:
      OPEN_AI_API_KEY: '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'
      OPEN_AI_PROXY: ''
      SINGLE_CHAT_PREFIX: '[""]'
      SINGLE_CHAT_REPLY_PREFIX: '"[阿罗] "'
      GROUP_CHAT_PREFIX: '["@bot"]'
      GROUP_NAME_WHITE_LIST: '["ChatGPT测试群", "ChatGPT测试群2"]'
      IMAGE_CREATE_PREFIX: '["画", "看", "找"]'
      CONVERSATION_MAX_TOKENS: 1000
      SPEECH_RECOGNITION: "False"
      CHARACTER_DESC: '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'
      EXPIRES_IN_SECONDS: 3600
      channel_type: "wechatcom_app",
      wechatcom_corp_id: "ww4f35fbcad6d02bfc", 
      wechatcomapp_token: "RlvIvgouaqYdUegqdnXmIR0",
      wechatcomapp_port: 9898,
      wechatcomapp_secret: "0ScZ9-06aYA1gRIvu4qvk__hrcgsxgyHQa5hH4370Ww",
      wechatcomapp_agent_id: "1000002",
      wechatcomapp_aes_key: "eGRhJChx2DnmbtqoWXRDnMPvlUakDXGk2jdsiiuuykX"
